spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/aims_test"
    username: root
    password: 1

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8080
  servlet:
    context-path: /aims_test
